Fix identation

diff --git a/bin/bin/own_script_notify_send_mpc_status b/bin/bin/own_script_notify_send_mpc_status
--- a/bin/bin/own_script_notify_send_mpc_status
+++ b/bin/bin/own_script_notify_send_mpc_status
@@ -30,11 +30,11 @@
 # Fetch album art information using playerctl, if it is installed.  Else
 # display generic icon.
 if [ "$(command -v playerctl 2> /dev/null)" ]; then
-	# TODO use paramater expansion instead of sed
-	album_art=$(playerctl metadata 'mpris:artUrl' --player=mpd | sed 's,file://,,')
+    # TODO use paramater expansion instead of sed
+    album_art=$(playerctl metadata 'mpris:artUrl' --player=mpd | sed 's,file://,,')
 else
-	# else use the "rhythmbox" icon from the available icon theme
-	album_art='rhythmbox'
+    # else use the "rhythmbox" icon from the available icon theme
+    album_art='rhythmbox'
 fi
 
 # The square brackets are meant to display their content only if the
@@ -45,15 +45,15 @@ mpc_format="$(mpc --format '%artist% - %title% == %album%[ (%date%)]' current)"
 # prints the notification to the terminal (stdout).  Otherwise it sends
 # a desktop notification (if the dependency is already installed).
 if [ "$1" == "cli" ]; then
-	echo "$mpc_format"
-	echo "Album art: $album_art"
+    echo "$mpc_format"
+    echo "Album art: $album_art"
 else
-	if [ "$(command -v notify-send 2> /dev/null)" ]; then
-		notify-send -i "$album_art" "Now Playing" "$mpc_format"
-	else
-		echo "ERROR. Missing Debian buster dependency 'libnotify-bin'"
-		echo "Cannot send desktop notification"
-		echo "Aborting"
-		exit 1
-	fi
+    if [ "$(command -v notify-send 2> /dev/null)" ]; then
+        notify-send -i "$album_art" "Now Playing" "$mpc_format"
+    else
+        echo "ERROR. Missing Debian buster dependency 'libnotify-bin'"
+        echo "Cannot send desktop notification"
+        echo "Aborting"
+        exit 1
+    fi
 fi
